"""create orders table with user_id

Revision ID: 24fa546d7521
Revises: 
Create Date: 2026-06-05 18:56:49.447725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fa546d7521'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_orders_reference_id', 'orders', ['reference_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_reference_id', 'orders', type_='unique')
    op.drop_column('orders', 'reference_id')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
