"""add processed_events table

Revision ID: 7ad68a74f33f
Revises: 24fa546d7521
Create Date: 2026-09-05 13:57:25.035993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad68a74f33f'
down_revision: Union[str, Sequence[str], None] = '24fa546d7521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.add_column('orders', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['reference_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'reference_id')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
